name: phonics_abc_app
description: "A phonics learning app for young English learners to practice the alphabet."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon/app_icon_foreground.png"
  image_path_ios: "assets/images/app_icon/app_icon_foreground.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon/app_icon_foreground.png"
  adaptive_icon_background: "assets/images/app_icon/app_icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
